version: '3'

services:
  app:
    build: app
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_ENV: development
      S3_BUCKET: image-processing-181562662531
    volumes:
        - src:/var/app/src

  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  src: {}